
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-ZipCode-Controller","number":29,"title":"Add ZipCode Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/29"},{"author":{"id":"MDQ6VXNlcjM1MjY0NzIx","is_bot":false,"login":"alexkxu","name":"Alex Xu"},"headRefName":"Alex-Joke-Controller","number":28,"title":"Add joke controller and test","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/28"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"Adam-Locations-Controller","number":26,"title":"added controller and test code for location","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/26"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"AmgadHawari-PublicHoliday","number":25,"title":"Amgad hawari public holiday","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/25"}]
