
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-READMEFixes","number":32,"title":"modified readme","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/32"},{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-University-Controller","number":30,"title":"Added University Controllers and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/30"},{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-ZipCode-Controller","number":29,"title":"Add ZipCode Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/29"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"AmgadHawari-PublicHoliday","number":25,"title":"Amgad hawari public holiday","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/25"}]
