
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"AmgadHawari-PublicHoliday","number":25,"title":"Amgad hawari public holiday","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/25"},{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-ZipCode","number":23,"title":"Add ZipCode Service","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/23"},{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-tides","number":22,"title":"Added TideService and test","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/22"},{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-University","number":20,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/20"},{"author":{"id":"MDQ6VXNlcjM1MjY0NzIx","is_bot":false,"login":"alexkxu","name":"Alex Xu"},"headRefName":"Alex-Joke","number":19,"title":"Add Joke Service","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-2/pull/19"}]
